### ISSUE TITLE
Test action

### ISSUE THREAD

**Issue by COil** [lennerd/VipxBotDetectBundle#11]
I have created a little action that allows to test user agent manually just with a get method, like this:

    http://dev.front.app.com/app_dev.php/testBotDetector?user-agent=ltx71%20-%20(http://ltx71.com/)

Outputs:

    tested User agent: "ltx71 - (http://ltx71.com/)"
    Name: ltx71
    Type: bot
    Metas:
        email: research@ltx71.com
        website: http://ltx71.com/

Do you think it is worth including it in the bundle ?

**Comment by lennerd** [comment]
Nice! If you like, you can add a little section to the readme explaining how you implemented this. Propably a nice little example for others.
