### ISSUE TITLE
Fix incorrect class name in services definition on branche 2.0

### ISSUE THREAD

**Issue by everhee** [lennerd/VipxBotDetectBundle#16]
Hello,
Could you also include in branche 2.0, the correction made on class name definition in this commit:
https://github.com/lennerd/VipxBotDetectBundle/commit/8df53427a69296aaf0919bf9768814bcb296a195
The v2's bundle also encounter some problems because of this incorrect class name definition.
Thanks

**Comment by lennerd** [comment]
Pretty busy right now. Are you able to create a PR against the `2.0` branch? Will add a corresponding tag then.

**Comment by lennerd** [comment]
Closed this PR, because `2.0` is now older than a year. Please use the newest version of the bundle.
