### ISSUE TITLE
Compatibility of DetectBundle with Symfony 4

### ISSUE THREAD

**Issue by NicoHaase** [lennerd/VipxBotDetectBundle#26]
Hi there,
thanks for your great bundle! We would like to upgrade our application to Symfony 4, but we also need your bundle and it is hardwired to Sf3. Do you see any chance for an upgrade?
Regards
Nico

**Comment by lennerd** [comment]
Hey @NicoHaase, nice to hear! 🙂

We are working on fixing the Travis testing setup at the moment. As soon as this is fixed we would like to add Symfony 2.* and Symfony 4 to composer requirements and the testing matrix.

I'm a little short on time. If you are willing to help by giving a PR that'd be great!

**Comment by NicoHaase** [comment]
Hi Lennart,
it's been a while since my last post here. Just wanted to come back to you and ask if there is anything to help you with? Is it just the test setup that is missing currently?
Regards
Nico

**Comment by lennerd** [comment]
@NicoHaase There is some work in #28 which still needs to be discussed but is a great step forward. I will try to create a new PR today. This should fix the Travis setup and testing matrix to be compatibly with Symfony 4 and PHP 7.

**Comment by lennerd** [comment]
@NicoHaase A new release supporting Symfony 4 is on its way! Hope you like it. See #29 for more information.
