### ISSUE TITLE
There is not way to white-list bot from extended_bot

### ISSUE THREAD

**Issue by vishalmelmatti** [lennerd/VipxBotDetectBundle#27]
I need to whitelist curl from extended_bot but there is not way to do it.

**Comment by COil** [comment]
Hi

**Comment by lennerd** [comment]
Sorry, I'm a little confused. Aren't you able to set all information yourself when using curl? And even more confusing: does the library detect curl request as bot requests? That might indeed be a bug.

**Comment by lennerd** [comment]
@vishalmelmatti ping.
