### ISSUE TITLE
User agent is not trimmed

### ISSUE THREAD

**Issue by COil** [lennerd/VipxBotDetectBundle#9]
When user agent is empty '', the bot "Aboutus" is reported. When the user agent is 1 space " " , the bot is not detected, shouldn’t the user be trimmed before calling the detect method ?

            $request->server->set('HTTP_USER_AGENT', '');
            dump($this->get('vipx_bot_detect.detector')->detectFromRequest($request));

            $request->server->set('HTTP_USER_AGENT', ' ');
            dump($this->get('vipx_bot_detect.detector')->detectFromRequest($request)); die();

Outputs:

    Controller.php on line 91:
    Metadata {#436 ▼
      -name: "AboutUs"
      -agent: ""
      -ip: null
      -type: "bot"
      -meta: array:1 [▶]
      -agentMatch: "exact"
    }
    Controller.php on line 94:
    null

**Comment by lennerd** [comment]
Good catch. Would you like to make a PR for this?

**Comment by lennerd** [comment]
Btw. this should be an issue of the [vipx-bot-detect](https://github.com/lennerd/vipx-bot-detect) package.
